# Generated by Django 5.1.7 on 2025-03-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_petitionsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='answear',
            field=models.TextField(blank=True, null=True),
        ),
    ]
